"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

add_newline = true
command_timeout = 1000

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$golang\
$helm\
$nodejs\
$deno\
$python\
$pulumi\
$terraform\
$aws\
$azure\
$kubernetes\
$env_var\
$sudo\
$cmd_duration\
$line_break\
$status\
$shell\
$character
"""

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "…/"
style = "bold cyan"

[git_branch]
format = 'on [$branch(:$remote_branch)]($style) '
style = "bold fg:#f1502f"

[golang]
format = "via [go ($version )]($style)"
version_format = "${raw}"
style = "bold cyan"

[nodejs]
format = "via [node ($version )]($style)"
version_format = "${raw}"
style = "bold green"

[python]
format = "via [python ($version )]($style)"
version_format = "${raw}"
style = "bold yellow"

[pulumi]
format = "in [($stack )]($style)"
style = "bold purple"

[aws]
format = 'as [($profile)(/$region) ]($style)'
style = "bold fg:#ff9900"

[aws.region_aliases]
us-east-1 = "IAD"
us-west-2 = "PDX"
eu-west-2 = "LHR"
ap-southeast-2 = "SYD"

[kubernetes]
disabled = false
format = "in [($context)(/$namespace) ]($style)"
style = "bold fg:#326ce5"

[cmd_duration]
disabled = true
format = "took [$duration]($style) "
style = "bold yellow"
min_time = 1

[character]
success_symbol = "[\u279c](bold green)"
error_symbol = "[\u279c](bold red)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
